services:
  kocka:
    container_name: kocka-server
    build: .
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./main.php:/var/www/main.php
      - ./core:/var/www/app/core
      - ./handlers:/var/www/app/handlers
      - ./middlewares:/var/www/app/middlewares
      - ./models:/var/www/app/models
    ports:
      - 80:80
